################################################################################
################################################################################
#
# APPLICATION CONFIGURATION
#
################################################################################
################################################################################

################################################################################
### eLDS Auth ontology
################################################################################
authOntology:
  abox:
    prefix: "http://eccenca.com/"
  accessConditions:
    url: "/opt/elds/etc/dataplatform/accessConditions.ttl"


################################################################################
### OAuth 2
################################################################################
oauth2:
  anonymous: true
  clients:
    - id: "eldsClient"
      secret: "secret"
      grantTypes:
        - "implicit"
        - "authorization_code"
      redirectUris:
        - "http://docker.local:8080/login"
        - "http://docker.local:8080/dataintegration/login"
        - "http://localhost:8080/login"
        - "http://localhost:8080/dataintegration/login"


################################################################################
### Authentication
################################################################################
authentication:
  inMemory:
    users:
      - username: "userA"
        password: "userA"
        groups:
          - "group_user"
          - "group_user_a"
      - username: "userB"
        password: "userB"
        groups:
          - "group_user"
          - "group_user_b"


################################################################################
### Security
################################################################################
http:
  cors:
    enabled: true # default false
    allowOriginRegex: ".*"


################################################################################
### SPARQL endpoints
################################################################################
sparqlEndpoints:
  owlImportsResolution: true
  stardog:
  - id: "default"
    authorization: REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
    host: "stardog"
    port: "5820"
    username: "admin"
    password: "admin"
    database: "stardog"
    versioningEnabled: true # optional, default false cached: <boolean> # optional, default false


################################################################################
### Proxy
################################################################################
proxy:
  - "default"


################################################################################
### Logging
################################################################################
logging:
  file: "/opt/elds/etc/dataplatform.log"
  level:
    root: WARN
    com.eccenca: INFO
    org.springframework: WARN
