authorization:
  abox:
    prefix: "http://eccenca.com/"
  accessConditions:
    url: "/opt/elds/etc/dataplatform/accessConditions.ttl"

oauth2:
  clients:
    - id: "eldsClient"
      secret: "secret"
      grantTypes:
        - "implicit"
        - "authorization_code"
        - "password"

authentication:
  inMemory:
    users:
      - username: "userA"
        password: "userA"
        groups:
          - "group_user"
          - "group_user_a"
      - username: "userB"
        password: "userB"
        groups:
          - "group_user"
          - "group_user_b"

http:
  cors:
    enabled: true
    allowOriginRegex: ".*"

proxy:
  - "default"

logging:
  file: "/opt/elds/var/log/dataplatform.log"
  level:
    root: WARN
    com.eccenca.elds.backend: INFO
    org.springframework: WARN

sparqlEndpoints:
  owlImportsResolution: true

---

###
# Stardog Spring profile
###
spring:
  profiles: stardog

sparqlEndpoints:
  stardog:
  - id: "default"
    authorization: REWRITE_FROM
    host: "stardog"
    port: "5820"
    username: "admin"
    password: "admin"
    database: "stardog"
    versioning:
      enabled: true

---

###
# Virtuoso Spring profile
###
spring:
  profiles: virtuoso

sparqlEndpoints:
  virtuoso:
    - id : "default"
      authorization : REWRITE_FROM
      host : "virtuoso"
      port : "1111"
      username : "dba"
      password : "dba"
      versioning:
        enabled: false
