################################################################################
################################################################################
#
# APPLICATION CONFIGURATION
#
################################################################################
################################################################################

################################################################################
### eLDS Auth ontology
################################################################################
authorization:
  abox:
    prefix: "http://eccenca.com/"
#    adminGroup: "ECCENCA-GMBH"
  accessConditions:
    url: "/opt/elds/etc/dataplatform/accessConditions.ttl"

################################################################################
### OAuth 2
################################################################################
oauth2:
  anonymous: true
  clients:
    - id: "eldsClient"
      secret: "secret"
      grantTypes:
        - "implicit"
        - "authorization_code"
        - "password"
        - "refresh_token"

################################################################################
### Authentication
################################################################################
authentication:
  inMemory:
    users:
      - username: "userA"
        password: "userA"
        groups:
          - "group_user"
          - "group_user_a"
      - username: "userB"
        password: "userB"
        groups:
          - "group_user"
          - "group_user_b"

################################################################################
### Security
################################################################################
http:
  cors:
    enabled: true # default false
    allowOriginRegex: ".*"

################################################################################
### Proxy
################################################################################
proxy:
  endpointIds:
    - "default"

################################################################################
### Logging
################################################################################
logging:
  file: "/opt/elds/etc/dataplatform.log"
  level:
    com.eccenca.elds.backend: DEBUG # default INFO
    org.springframework: INFO
    # com.eccenca.elds.backend.stardog: INFO
    # com.eccenca.elds.backend.webapp.config: INFO

################################################################################
### SPARQL endpoints
################################################################################
sparqlEndpoints:
  owlImportsResolution: true

---

###
# Configuration for stardog sparql endpoint
###
spring:
  profiles: stardog

sparqlEndpoints:
  stardog:
  - id: "default"
    authorization: REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
    host: "stardog"
    port: "5820"
    username: "admin"
    password: "admin"
    database: "stardog"
    versioning:
      enabled: true

---

###
# Configuration for virtuoso sparql endpoint
###
spring:
  profiles: virtuoso

sparqlEndpoints:
  virtuoso:
    - id : "default"
      authorization : REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
      host : "virtuoso"
      port : "1111"
      username : "dba"
      password : "dba"
      versioning:
        enabled: false

---

###
# Configuration for apache marmotta sparql endpoint http://marmotta.apache.org/
###
spring:
  profiles: marmotta

sparqlEndpoints:
  http:
  - id: 'default'
    authorization: REWRITE_FROM
    queryEndpointUrl:  'http://marmotta:8080/marmotta/sparql/select'
    updateEndpointUrl: 'http://marmotta:8080/marmotta/sparql/update'
    sync:
      subscriber:
        enabled: false # default true
      publisher:
        enabled: false

---

###
# Configuration for systap-blazegraph
###
spring:
  profiles: blazegraph

sparqlEndpoints:
  http:
  - id: 'default'
    authorization: REWRITE_FROM
    queryEndpointUrl:  'http://blazegraph:9999/bigdata/sparql'
    updateEndpointUrl: 'http://blazegraph:9999/bigdata/sparql'
    sync:
      subscriber:
        enabled: false # default true
      publisher:
        enabled: false
