################################################################################
################################################################################
#
# APPLICATION CONFIGURATION
#
################################################################################
################################################################################

################################################################################
### eLDS Auth ontology
################################################################################
authorization:
  abox:
    prefix: "http://eccenca.com/"
  accessConditions:
    url: "/opt/elds/etc/dataplatform/accessConditions.ttl"


################################################################################
### OAuth 2
################################################################################
oauth2:
  anonymous: true
  clients:
    - id: "eldsClient"
      secret: "secret"
      grantTypes:
        - "implicit"
        - "authorization_code"
        - "password"

################################################################################
### Authentication
################################################################################
authentication:
  inMemory:
    users:
      - username: "userA"
        password: "userA"
        groups:
          - "group_user"
          - "group_user_a"
      - username: "userB"
        password: "userB"
        groups:
          - "group_user"
          - "group_user_b"


################################################################################
### Security
################################################################################
http:
  cors:
    enabled: true # default false
    allowOriginRegex: ".*"

################################################################################
### Proxy
################################################################################
proxy:
  - "default"


################################################################################
### Logging
################################################################################
logging:
  file: "/opt/elds/var/log/dataplatform.log"
  level:
    root: WARN
    com.eccenca.elds.backend: INFO
    org.springframework: WARN

################################################################################
### SPARQL endpoints
################################################################################
sparqlEndpoints:
  owlImportsResolution: true

---

###
# Configuration for stardog sparql endpoint
###
spring:
  profiles: stardog
  autoconfigure:
      exclude:
        # disable dataSource auto-config as it breaks dataSource-less deployment in a servlet container
        - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
        # disable transaction management as it breaks spring-security-oauth
        - "org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration"


sparqlEndpoints:
  stardog:
  - id: "default"
    authorization: REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
    host: "stardog"
    port: "5820"
    username: "admin"
    password: "admin"
    database: "stardog"
    versioning:
      enabled: true

---

###
# Configuration for virtuoso sparql endpoint
###
spring:
  profiles: virtuoso
  autoconfigure:
      exclude:
        # disable dataSource auto-config as it breaks dataSource-less deployment in a servlet container
        - "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
        # disable transaction management as it breaks spring-security-oauth
        - "org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration"


sparqlEndpoints:
  virtuoso:
    - id : "default"
      authorization : REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
      host : "virtuoso"
      port : "1111"
      username : "dba"
      password : "dba"
      versioning:
        enabled: false
