version: '2'
services:
  cmem:
    build: cmem/
    hostname: docker.local
    environment:
      CATALINA_OPTS: "-Xmx2g -XX:MaxPermSize=512m -Dspring.profiles.active=marmotta"
    volumes:
      - ./etc:/opt/elds/etc
      - ./data:/data
      - ./data/dataintegration/datalake:/opt/elds/var/dataintegration/resources
    ports:
      - "80:8080"
    depends_on:
      - marmotta
    links:
      - marmotta
  marmotta:
    image: apache/marmotta
#    volumes:
#      - virtuoso-data:/data
    ports:
      - "8080:8080"

#volumes:
#  virtuoso-data:
#    external:
#      name: virtuoso-data
