version: '2'
services:
  elds:
    build: .
    hostname: docker.local
    volumes:
      - ./etc:/opt/elds/etc
    ports:
      - "8080:8080"
    depends_on:
      - virtuoso
    links:
      - virtuoso
  virtuoso:
    image: eccenca/virtuoso7:7.2.0.1-3