version: '2'
services:
  cmem:
    image: eccenca/cmem:v2.3.1
    build: cmem/
    hostname: docker.local
    environment:
      CATALINA_OPTS: "-Xmx4g -Dspring.profiles.active=stardog"
    volumes:
      - ./etc:/opt/elds/etc
      - ./data:/data
      - ./data/dataintegration/datalake:/opt/elds/var/dataintegration/resources
    ports:
      - "8080:8080"
    depends_on:
      - stardog
    links:
      - stardog
  stardog:
    image: eccenca/stardog:v4.2.3
    build: stardog/
    volumes:
      - stardog-data:/data
    ports:
      - "5820:5820"

volumes:
  stardog-data:
    external:
      name: stardog-data
