version: '2'
services:
  cmem:
    build: cmem/
    hostname: docker.local
    environment:
      CATALINA_OPTS: "-Xmx6g -Dspring.profiles.active=stardog"
    volumes:
      - ./etc:/opt/elds/etc
      - ./data:/data
      - ./data/dataintegration/datalake:/opt/elds/var/dataintegration/resources
    ports:
      - "8080:8080"
    depends_on:
      - stardog
    links:
      - stardog
  stardog:
    build: stardog/
    volumes:
      - stardog-data:/data
    ports:
      - "5820:5820"
    environment:
      - "JAVA_MAX_MEM=2g"

volumes:
  stardog-data:
    external:
      name: stardog-data
