version: '2'
services:
  cmem:
    image: eccenca/cmem:v2.3.1
    build: cmem/
    hostname: docker.local
    environment:
      CATALINA_OPTS: "-Xmx4g -Dspring.profiles.active=virtuoso"
    volumes:
      - ./etc:/opt/elds/etc
      - ./data:/data
      - ./data/dataintegration/datalake:/opt/elds/var/dataintegration/resources
    ports:
      - "8080:8080"
    depends_on:
      - virtuoso
    links:
      - virtuoso
  virtuoso:
    image: eccenca/virtuoso7:7.2.0.1-3
    volumes:
      - virtuoso-data:/data
    ports:
      - "8890:8890"

volumes:
  virtuoso-data:
    external:
      name: virtuoso-data
