version: '2'
services:
  elds:
    build: .
    hostname: docker.local
    environment:
      CATALINA_OPTS: "-Xmx2g -XX:MaxPermSize=512m"
    volumes:
      - ./etc:/opt/elds/etc
    ports:
      - "8080:8080"
    depends_on:
      - stardog
    links:
      - stardog
  stardog:
    image: stardog:4.1.1
    ports:
      - "5820:5820"