js.config.properties.rootObject.workspaces: |
  [{
    "endpoint": "http://docker.local:8080/dataplatform",
    "endpointId": "default",
    "endpointName": "Default endpoint",
    "defaultGraph": "",
    "authorizationType": "oauth2",
    "oauth2": {
        "grantType": "implicit",
        "authorizeEndpoint": "http://docker.local:8080/dataplatform/oauth/authorize",
        "clientId": "eldsClient"
    },
    "appPresentation": {
        "name": "eccenca Corporate Memory",
        "title": "eccenca Corporate Memory"
    }
  }]
js.config.properties.rootObject.hideEndpointInput: false

js.config.properties.rootObject.appPresentation: |
  {
    "name": "eccenca Corporate Memory",
    "title": "eccenca Corporate Memory"
  }

js.config.properties.rootObject.rdfdoc: |
  {
    "fallbackOntology": true,
    "fallbackSchema": false
  }
  
js.config.properties.rootObject.dataintegration: |
  {
    "urlRestApi": "http://docker.local:8080/dataintegration/",
    "dummyDefaultProjectId": "cmem"
  }

js.config.properties.rootObject.datasetManagement: |
  {
    "graph": "https://ns.eccenca.com/example/data/dataset/"
  }

js.config.properties.rootObject.vocabularyManagement: |
  {
    "graph": "https://ns.eccenca.com/example/data/vocabs/"
  }

###########
# Logging #
###########
logging.file: "/opt/elds/etc/datamanager.log"