js.config.properties.rootObject.workspaces: |
  [{
    "endpoint": "http://docker.local:8080/dataplatform",
    "endpointId": "default",
    "endpointName": "Default endpoint",
    "defaultGraph": "",
    "authorizationType": "oauth2",
    "oauth2": {
        "grantType": "implicit",
        "authorizeEndpoint": "http://docker.local:8080/dataplatform/oauth/authorize",
        "clientId": "eldsClient"
    }
  }]
js.config.properties.rootObject.hideEndpointInput: false
js.config.properties.rootObject.rdfdoc: |
  {
    "fallbackOntology": true,
    "fallbackSchema": false
  }
#js.config.properties.rootObject.dataintegration: |
#  {
#    "graph": "https://ns.eccenca.com/example/data/dataset/",
#    "urlRestApi": "//docker.local:8080/dataintegration",
#    "dummyDefaultProjectId": "AXA"
#  }

###########
# Logging #
###########
logging.file: "/opt/elds/etc/datamanager.log"