js.config.workspaces:
  default:
    name: eccenca Corporate Memory (Port 8080)
    backend:
      type: dataplatform
      url: "http://docker.local:8080/dataplatform"
      endpointId: default
    authorization:
      type: oauth2
      oauth2:
        clientId: eldsClient
        grantType: implicit
        authorizeUrl: "http://docker.local:8080/dataplatform/oauth/authorize"
  default80:
    name: eccenca Corporate Memory (Port 80)
    backend:
      type: dataplatform
      url: "http://docker.local/dataplatform"
      endpointId: default
    authorization:
      type: oauth2
      oauth2:
        clientId: eldsClient
        grantType: implicit
        authorizeUrl: "http://docker.local/dataplatform/oauth/authorize"

js.config.appPresentation:
  headerName: eccenca Corporate Memory
  windowTitle: eccenca Corporate Memory

js.config.modules.datasets:
  enable: true
  startWith: true
  graphUrl: "https://ns.eccenca.com/example/data/dataset/"
  dataintegration:
    url: "http://docker.local:8080/dataintegration/"
    includeOAuthToken: true
    project: cmem

js.config.modules.explore:
  enable: true
  graphlist:
    listQuery: |
      SELECT DISTINCT ?g WHERE {
        GRAPH ?g { ?s ?p ?o }
        FILTER (?g NOT IN (<http://www.w3.org/2002/07/owl#>,<http://www.w3.org/ns/ldp#>)) .
      }

js.config.modules.vocabulary:
  enable: true
  graphUrl: "https://ns.eccenca.com/example/data/vocabs/"

###########
# Logging #
###########
logging.file: "/opt/elds/etc/datamanager.log"
