apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmem-persistent-storage
  namespace: cmem-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      repl: "1"
