apiVersion: v1
kind: ConfigMap
metadata:
  name: cmem-dataintegration-config
  namespace: cmem-k8s
data:
  dataintegration.conf: |
    #################################################

    # Play specific settings
    #################################################

    # The secret used for cryptography
    play.crypto.secret = "QCY?tAnfk?aZ?iwKNwnxIyuihB`R5W:(/uDFN];Ik@n"
    play.crypto.secret = ${?DATAINTEGRATION_APPLICATION_SECRET}

    # The application loader
    play.application.loader = "EccencaApplicationLoader"

    # set application context
    play.http.context= "/dataintegration"
    play.http.context= ${?DATAINTEGRATION_CONTEXT}

    # set application max upload file size
    play.http.parser.maxDiskBuffer=1024MB

    #################################################
    # eccenca DataPlatform
    #################################################

    # The URL of the eccenca DataPlatform
    eccencaDataPlatform.url = ${DEPLOY_BASE_URL}"/dataplatform"
    eccencaDataPlatform.endpointId = "default"
    eccencaDataPlatform.oauth = true
    oauth.clientId = "eldsClient"
    oauth.clientSecret = "secret"
    oauth.authorizationUrl = ${eccencaDataPlatform.url}"/oauth/authorize"
    oauth.tokenUrl = ${eccencaDataPlatform.url}"/oauth/token"

    # Define the protocol used for accessing the workbench (http or https), defaults to http
    workbench.protocol = ${?DEPLOY_PROTOCOL}

    #################################################
    # Workspace
    #################################################
    elds.home = /opt/elds

    # Set the used workspace
    workspace.provider.plugin = backend

    workspace.repository.plugin = file

    # Workspace on filesystem
    workspace.provider.file = {
      dir = "/opt/elds/var/dataintegration/workspace/"
    }

    # hide header
    workbench.showHeader=false

    # File-based workspace that allows to export projects as RDF files
    workspace.provider.rdfExport = {
      dir = "/opt/elds/var/dataintegration/workspace/"
    }

    # Workspace on the RDF store (requires backend.url parameter to be defined)
    workspace.provider.backend = {
      dir = "/opt/elds/var/dataintegration/workspace/" # Optional: File system path for holding resources, such as input datasets
    }

    workflow.executor.plugin = ${DATAINTEGRATION_EXECUTOR}

    #################################################
    # Internal Dataset
    #################################################

    # dataset.internal.plugin = inMemory
    dataset.internal.plugin = eccencaDataPlatform

    dataset.internal.eccencaDataPlatform = {
      graph = "https://eccenca.com/dataintegration/internal"
    }


    #################################################
    # Logging
    #################################################
    # logger.file=/opt/elds/etc/dataintegration/logback.xml
    # All log messages
    logger.root=INFO
    # Play framework specific log messages
    logger.play=INFO
    # OAuth specific log messages
    logger.oauth=DEBUG
