apiVersion: v1
kind: ConfigMap
metadata:
  name: cmem-dataplatform-config
  namespace: cmem-k8s
data:
  application.yml: |
    ################################################################################
    ################################################################################
    #
    # APPLICATION CONFIGURATION
    #
    ################################################################################
    ################################################################################
    spring:
      http:
        multipart:
          maxFileSize: 4096MB
          maxRequestSize: 4096MB
      cache:
        type: REDIS
      redis:
        host: "cmem-cache"
        port: 6379
    ################################################################################
    ### eLDS Auth ontology
    ################################################################################
    authorization:
      abox:
        prefix: "http://eccenca.com/"
      accessConditions:
        url: "/opt/elds/etc/dataplatform/accessConditions.ttl"


    ################################################################################
    ### OAuth 2
    ################################################################################
    oauth2:
      anonymous: true
      jwt:
        enabled: true
      clients:
        - id: "eldsClient"
          secret: "secret"
          grantTypes:
            - "implicit"
            - "authorization_code"
            - "password"

    ################################################################################
    ### Authentication
    ################################################################################
    authentication:
      inMemory:
        users:
          - username: "userA"
            password: "userA"
            groups:
              - "group_user"
              - "group_user_a"
          - username: "userB"
            password: "userB"
            groups:
              - "group_user"
              - "group_user_b"


    ################################################################################
    ### Security
    ################################################################################
    http:
      cors:
        enabled: true # default false
        allowOriginRegex: ".*"

    ################################################################################
    ### Proxy
    ################################################################################
    proxy:
      - "default"


    ################################################################################
    ### Logging
    ################################################################################
    logging:
      file: "/opt/elds/var/log/dataplatform.log"
      level:
        root: WARN
        com.eccenca.elds.backend: INFO
        org.springframework: WARN

    ################################################################################
    ### SPARQL endpoints
    ################################################################################
    sparqlEndpoints:
      owlImportsResolution: true

    ---

    ###
    # Configuration for stardog sparql endpoint
    ###
    spring:
      profiles: stardog

    sparqlEndpoints:
      stardog:
      - id: "default"
        authorization: REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
        host : "cmem-database"
        port: "5820"
        username: "admin"
        password: "admin"
        database: "stardog"
        versioning:
          enabled: true

    ---

    ###
    # Configuration for virtuoso sparql endpoint
    ###
    spring:
      profiles: virtuoso

    sparqlEndpoints:
      virtuoso:
        - id : "default"
          authorization : REWRITE_FROM # PROVISIONED # REWRITE_FROM # PROVISIONED # optional, default NONE
          host : "virtuoso"
          port : "1111"
          username : "dba"
          password : "dba"
          versioning:
            enabled: false

  accessConditions.ttl: |
    @prefix eccauth: <https://vocab.eccenca.com/auth/> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .
    @prefix dc: <http://purl.org/dc/terms/>.
    @prefix : <http://eccenca.com/> .

    :ReadAllGraphsGroupUser a eccauth:AccessCondition ;
        rdfs:label "read only access" ;
        dc:creator <http://eccenca.com/eccencaGmbHDevOps> ;
        dc:created "2017-05-03T12:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        eccauth:requiresGroup :group_user ;
        eccauth:readGraph <urn:elds-backend-all-graphs>;
        eccauth:allowedAction <urn:elds-backend-actions-revision-api>, <urn:eccenca:di> ;
    .

    :WriteAllGraphsGroupUserB  a eccauth:AccessCondition ;
        rdfs:label "administrative access" ;
        dc:creator <http://eccenca.com/eccencaGmbHDevOps> ;
        dc:created "2017-05-03T12:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
            eccauth:requiresGroup :group_user, :group_user_b ;
        eccauth:writeGraph <urn:elds-backend-all-graphs>;
        eccauth:allowedAction <urn:elds-backend-actions-revision-api>, <urn:eccenca:di> ;
    .

    :AnonymousReadAccess a eccauth:AccessCondition ;
        rdfs:label "anonymous access" ;
        dc:creator <http://eccenca.com/eccencaGmbHDevOps> ;
        dc:created "2017-05-03T12:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        eccauth:requiresGroup <urn:elds-backend-public-group> ;
        eccauth:readGraph <urn:elds-backend-all-graphs> ;
        eccauth:allowedAction <urn:elds-backend-actions-revision-api>, <urn:eccenca:di> ;
    .

    # delete this access condition to remove write access for anonymous users
    :AnonymousWriteAccess a eccauth:AccessCondition ;
        rdfs:label "anonymous write access - be careful with this rule!" ;
        dc:creator <http://eccenca.com/eccencaGmbHDevOps> ;
        dc:created "2017-05-03T12:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        eccauth:requiresGroup :group_user, :group_user_b ;
        eccauth:requiresGroup <urn:elds-backend-public-group> ;
        eccauth:writeGraph <urn:elds-backend-all-graphs> ;
    .

    <http://eccenca.com/eccencaGmbHDevOps> rdfs:label "eccenca GmbH - DevOps Team".
